---
- name: Playbook
  hosts: webservers
  become: yes # If to escalate privilege
  become_method: sudo # Set become method
  remote_user: ubuntu # Update username for remote server
  ignore_unreachable: true
  ignore_errors: true
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop:
        [
          "apt-transport-https",
          "ca-certificates",
          "curl",
          "software-properties-common",
          "python3-pip",
          "virtualenv",
          "python3-setuptools",
        ]

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull default Docker image
      docker_image:
        name: praphull/restclient
        source: pull

    
    - name: Create default containers
      docker_container:
        name: praphullrestclient
        image: praphull/restclient
        state: present
      with_sequence: count=1
